export const BookingConstent={
    GET_LIST_OF_BOOKING_REQUEST : 'GET_LIST_OF_BOOKING_REQUEST',
    GET_LIST_OF_BOOKING_SUCCESS : 'GET_LIST_OF_BOOKING_SUCCESS',
    GET_LIST_OF_BOOKING_FAILURE : 'GET_LIST_OF_BOOKING_FAILURE',
}