export const ItemConstent={
    GET_ITEM_REQUEST : 'GET_ITEM_REQUEST',
    GET_ITEM_SUCCESS : 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILURE : 'GET_ITEM_FAILURE',

    //ListOfItems
    GET_LIST_OF_ITEMS_REQUEST : 'GET_LIST_OF_ITEMS_REQUEST',
    GET_LIST_OF_ITEMS_SUCCESS : 'GET_LIST_OF_ITEMS_SUCCESS',
    GET_LIST_OF_ITEMS_FAILURE : 'GET_LIST_OF_ITEMS_FAILURE',





}